name: ln_alerts
description: Ln alerts and managing them
version: 0.2.1
repository: https://github.com/orcunoz/ln_alerts
publish_to: none

environment:
  sdk: ^3.0.5

dependencies:
  flutter:
    sdk: flutter

  ln_core:
    path: ../core

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
