name: ln_alerts
description: Ln alerts and managing them
version: 0.8.0
repository: https://github.com/orcunoz/ln_alerts
publish_to: none

environment:
  sdk: ^3.0.5

dependencies:
  flutter:
    sdk: flutter

  stack_trace:
  ln_core:
    path: ../ln_core
    #git:
    #  url: https://github.com/orcunoz/ln_core
    #  ref: main

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
