name: ln_alerts
description: LnAlerts, creating and managing alerts
version: 0.9.1
repository: https://github.com/orcunoz/ln_alerts
publish_to: none

environment:
  sdk: ^3.0.5

dependencies:
  flutter:
    sdk: flutter

  stack_trace:
  ln_core:
    #path: ../ln_core
    git:
      url: https://github.com/orcunoz/ln_core
      ref: main

flutter:
  uses-material-design: true

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
